name: 'DocFX for GitHub Pages'
description: 'GitHub Actions to deploy C# / Unity API reference to GitHub Pages.'
author: 'Sator Imaging'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'upload-cloud'
  color: 'yellow'


inputs:

  # required options
  app_name:
    description: |
      Text shown next to header logo.
      Default 'docfx-pages'
    default:  'docfx-pages'
    required: true

  site_title:
    description: |
      Website title used as suffix for HTML pages. ex) "HTML Page Title | <site title>"
      Default 'DocFX for GitHub Pages'
    default:  'DocFX for GitHub Pages'
    required: true

  site_footer:
    description: |
      Footer text for generated pages. HTML accepted.
      Default '&copy; 2023 Sator Imaging'
    default:  '&copy; 2023 Sator Imaging'
    required: true

  # optional
  class_members:
    description: |
      Generate all-in-one class api document or separate each member into pages.
      Accepts one of: 'separatePages' | 'samePage'
      Default 'samePage'
    default:  'samePage'

  site_logo:
    description: |
      Website logo file path. Accepts full-qualified URI or relative path to '.docfx' folder.
      Default 'images/wikimedia-commons/logo-csharp-recolor.svg'
    default:  'images/wikimedia-commons/logo-csharp-recolor.svg'

  site_favicon:
    description: |
      Favicon file path. Accepts full-qualified URI or relative path to '.docfx' folder.
      Default 'images/wikimedia-commons/logo-csharp-recolor.svg'
    default:  'images/wikimedia-commons/logo-csharp-recolor.svg'

  google_analytics:
    description: |
      Google Analytics ID. Leave empty to disable this feature.
      Default ''
    default:  ''

  # customize main.js/css, see docfx reference for detail
  # https://dotnet.github.io/docfx/docs/template.html?tabs=modern#custom-template
  # note that these are added after builtin settings
  main_js:
    description: |
      Default ''
    default:  ''

  main_css:
    description: |
      Default ''
    default:  ''


outputs:
  page_url:
    description: 'URL to deployed GitHub Pages'
    value: ${{ steps.deployment.outputs.page_url }}


runs:
  using: "composite"
  steps:

    # do not checkout caller's repository.
    # it should be controlled by caller.

    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x


    - name: Checkout docfx-pages
      uses: actions/checkout@v3
      with:
        repository: 'sator-imaging/docfx-pages'
        sparse-checkout: '.docfx'
        sparse-checkout-cone-mode: true
        path: 'tmp-docfx-pages'
        # TODO: how to get specified version ('@*' at the end of 'uses' command)
        ref: 'v1'

    - name: Combine repository
      shell: bash
      run: |
        cp -n -r 'tmp-docfx-pages/.docfx' '.'
        rm -rf    tmp-docfx-pages

    - name: Rename README and LICENSE
      shell: bash
      run: |
        if test -f README; then
          if ! test -f README.md; then
            mv README README.md
          fi
        fi
        if test -f LICENSE; then
          if ! test -f LICENSE.md; then
            mv LICENSE LICENSE.md
          fi
        fi

    - name: Fix document title if required
      shell: bash
      run: |
        if test -f README.md; then
          if ! [ "$(head -1 README.md | sed -n '/^# /p;q')" ]; then
            echo "# $(cat README.md)" > README.md
          fi
        fi
        if test -f LICENSE.md; then
          if ! [ "$(head -1 LICENSE.md | sed -n '/^# /p;q')" ]; then
            echo "# $(cat LICENSE.md)" > LICENSE.md
          fi
        fi

    - name: Generate README.md and index.md
      shell: bash
      run: |
        if ! test -f 'README.md'; then
          echo "# $(echo ${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/})" > README.md
          echo "${{ github.server_url }}/${{ github.repository }}" >> README.md
        fi
        if ! test -f 'index.md'; then
          mv 'README.md' 'index.md'
        fi

    # api/toc.yml makes breadcrumb menu weird. waiting for future update.
    - name: Generate toc.yml
      shell: bash
      run: |
        cd .docfx
          if ! test -f 'toc.yml'; then
            echo '- name: API' >> 'toc.yml'
            echo '  href: api/toc.yml' >> 'toc.yml'
            echo '  expanded: true' >> 'toc.yml'
            if test -f '../LICENSE.md'; then
              echo '- name: License' >> 'toc.yml'
              echo '  href: LICENSE.html' >> 'toc.yml'
            fi
          fi
        cd ..

    - name: Generate docfx config
      shell: bash
      run: |
        cd .docfx

          printf "$(cat docfx.json)" \
            "${{ inputs.class_members }}" \
            "${{ inputs.app_name }}" \
            "${{ inputs.site_title }}" \
            "${{ inputs.site_footer }}" \
            "${{ inputs.site_logo }}" \
            "${{ inputs.site_favicon }}" \
            "${{ inputs.google_analytics }}" \
            > docfx.json

          echo "${{ inputs.main_js }}"  >> template/public/main.js
          echo "${{ inputs.main_css }}" >> template/public/main.css

        cd ..


    # DEBUG
    - name: DEBUG
      shell: bash
      run: |
        cat .docfx/docfx.json


    - name: Run DocFX
      shell: bash
      run: |
        dotnet tool update -g docfx
        docfx .docfx/docfx.json

    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        # Upload entire repository
        path: '.docfx/_site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
