# name is hard-coded in main branch workflow
name: 'Run Tests on main branch'

on:
  push:
    tags:
      - test

jobs:
  trigger_main_brunch:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Run Tests on main branch'
