name: Tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest


    ###########################################
    #######  sator-imaging/docfx-pages  #######
    ###########################################
    steps:
      - name: Checkout is required for testing
        uses: actions/checkout@v3

      - uses: ./   # replace to: sator-imaging/docfx-pages@v1
        id: deployment
        with:
          # required options  NOTE: double-quote (") cannot be used
          app_name: 'Deploy Test'
          site_title: 'Deploy Test using sator-imaging/docfx-pages'
          site_footer: '<big>&times; Is HTML accepted?</big>'

          # optional
          member_layout: 'separatePages'  # 'separatePages' or 'samePage'
          site_logo: 'https://avatars.githubusercontent.com/u/16752340'
          site_favicon: 'https://avatars.githubusercontent.com/u/45192683'
          google_analytics: ''  # empty to disable

          # main.js  see: https://dotnet.github.io/docfx/docs/template.html?tabs=modern#custom-template
          main_js: |
            export default {
                defaultTheme: "light",
                showLightbox: (img) => true,
                iconLinks: [
                    {
                        icon: 'github',
                        href: 'https://github.com/sator-imaging',
                        title: 'GitHub'
                    },
                    {
                        icon: 'twitter',
                        href: 'https://twitter.com/sator_imaging',
                        title: 'Twitter'
                    },
                    {
                        icon: 'youtube',
                        href: 'https://www.youtube.com/@SatorImaging',
                        title: 'YouTube'
                    },
                    {
                        icon: 'chat-quote-fill',
                        href: 'https://www.sator-imaging.com/',
                        title: 'Contact'
                    },
                ],
            }

          # main.css  see: https://dotnet.github.io/docfx/docs/template.html?tabs=modern#custom-template
          main_css: |
          
          
