name: Tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'releases/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest


    ###########################################
    #######  sator-imaging/docfx-pages  #######
    ###########################################
    steps:

      - name: Checkout
        uses: actions/checkout@v3


      - uses: sator-imaging/docfx-pages@v1
        id: deployment   # required to show link in workflow graph in actions result page.
        with:
          # required options  NOTE: double-quote (") cannot be used
          app_name: 'Deploy Test'
          site_title: 'Deploy Test using sator-imaging/docfx-pages'
          site_footer: '<big>&times; Is HTML accepted?</big>'

          # optional
          class_members: 'separatePages'  # 'separatePages' or 'samePage'
          google_analytics: ''  # empty to disable

          # paths must be relative from .docfx folder. url works but only in top page.
          site_logo: 'https://avatars.githubusercontent.com/u/16752340'     
          site_favicon: 'https://avatars.githubusercontent.com/u/45192683'

          # advanced options
          # --> https://dotnet.github.io/docfx/docs/template.html?tabs=modern#custom-template
          # main.js
          # NOTE: double-quote (") cannot be used
          main_js: |
            export default {
                defaultTheme: 'light',
                showLightbox: (img) => true,
                iconLinks: [
                    {
                        icon: 'github',
                        href: 'https://github.com/sator-imaging',
                        title: 'GitHub'
                    },
                ],
            }

          # main.css
          # NOTE: double-quote (") cannot be used
          main_css: |
          
          
